#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm format:fix
pnpm lint

# Re-add only the files that were originally staged and still exist
git diff --cached --name-only | while read -r file; do
    if [ -f "$file" ]; then
    git add "$file"
  fi
done